Reason: add new cleaning

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,5 +1,5 @@
 #!/bin/bash
-#PBS -l nodes=1:ppn=8,vmem=16g,walltime=16:00:00
+#PBS -l nodes=1:ppn=8,vmem=16g,walltime=10:00:00
 #PBS -N roi2roitrack
 #PBS -V
 
@@ -36,10 +36,10 @@ mv output.mat ./wmc/classification.mat
 mv tracts ./wmc/
 mv output_fibercounts.txt ./wmc/
 
-if [ -f ./wmc/classification.mat ]; then
-	rm -rf *.nii.gz*
-	exit 0
-else
-	echo "tracking failed"
-	exit 1
-fi
+#if [ -f ./wmc/classification.mat ]; then
+#	rm -rf *.nii.gz*
+#	exit 0
+#else
+#	echo "tracking failed"
+#	exit 1
+#fi
